//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiraApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Department = new HashSet<Department>();
        }
    
        public int CompanyId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string RegestrationNumber { get; set; }
        public string Phone { get; set; }
        public string PoBox { get; set; }
        public string Logo { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual CompanySize CompanySize { get; set; }
        public virtual IndustryType IndustryType { get; set; }
        public virtual LineOfDefence LineOfDefence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Department { get; set; }
    }
}
