//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiraApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageDictionary
    {
        public int LanguageDictionaryId { get; set; }
        public string KeyIndex { get; set; }
        public string ArabicTranslation { get; set; }
        public string EnglishTranslation { get; set; }
    }
}
